services:
  mongo:
    image: mongo:6
    container_name: upivot-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: upivot-api
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/upivot
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - COOKIE_SAME_SITE=${COOKIE_SAME_SITE}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=http://localhost:4000/auth/google/callback
      - WEB_ORIGIN=http://localhost:5173
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: upivot-web
    restart: always
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
    ports:
      - "5173:5173"
    depends_on:
      - api


volumes:
  mongo_data:
