services:
  mongo:
    image: mongo:6
    container_name: upivot-mongo-prod
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=upivot
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: upivot-api-prod
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/upivot
      - MONGO_DB_NAME=upivot
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME:-upivot_session}
      - COOKIE_SECURE=true
      - COOKIE_SAME_SITE=strict
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - WEB_ORIGIN=${WEB_ORIGIN}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-300000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-60}
    ports:
      - "4000:4000"
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: upivot-web-prod
    restart: always
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${API_BASE_URL}
    ports:
      - "80:5173"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:
