# Use node for building
FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json first
COPY package*.json ./

# Install deps
RUN npm install

# Copy rest of the frontend source
COPY . .

# Expose Vite dev port
EXPOSE 5173

# Start Vite
CMD ["npm", "run", "dev", "--", "--host"]
